@startuml AsIsContext
title Теплый Дом As Is Context Diagram

top to bottom direction

!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Component.puml

Person(user, "Пользователь", "Включает и выключает устройства, настраивает температурный режим")
Person(admin, "Администратор", "управление пользователями, удаленная настройка устройств")
Person(Specialist, "Выездной Специалист ", "Устанавливает и настраивает устройства на локации пользователя")
System(HeatingSystem, "HeatingSystem", "Система управляет температурой в домах")

System_Ext(IotApi, "Устройства управления температурой", "Сбор информации с датчиков устройств")

Rel(user, HeatingSystem, "Пользуется системой")
Rel(admin,HeatingSystem,"Администрирует систему, проводит удаленную настройку устройств")
Rel(Specialist, HeatingSystem, "Производит первичную настройку устройств")
Rel(HeatingSystem,IotApi,"Управление устройствами")

@enduml